name: fitzone
description: "Aplicación móvil FitZone para gestión de gimnasio."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Iconos de estilo iOS
  cupertino_icons: ^1.0.8

  # Cliente HTTP para conectar con la API Node.js/MongoDB del Backend
  http: ^1.2.0

  # Gestor de estado para manejar la sesión del usuario y datos de la app
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/